services:
  - type: web
    name: bunny-farm-api
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: .
    buildCommand: pnpm install && pnpm build --filter=bunny-farm-api
    startCommand: pnpm --filter=bunny-farm-api start
